### PR TITLE
Feature/10 add verbose option

### PR DESCRIPTION
**Pull request by hhedden-isovera**

### CODE REVIEW

**Review by amanire — CHANGES_REQUESTED** [review]
I just ran this and it appeared to work great, but the labels are not actually in [the repo](https://github.com/isovera/temp-test/labels).

```sh
$ ./enlabeler.sh 
Welcome to Enlabeler!
Credentials required: Github username/password
GitHub User: amanire
GitHub Password (or token if using 2fa): 
GitHub Repo (expected format is 'owner/repository' e.g. 'isovera/enlabeler'): isovera/temp-test
Would you like to delete obsolete labels? (Y/N):Y
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   138  100   138    0     0    579      0 --:--:-- --:--:-- --:--:--   582
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   138  100   138    0     0    776      0 --:--:-- --:--:-- --:--:--   779
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    98  100    98    0     0    576      0 --:--:-- --:--:-- --:--:--   573
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   124  100   124    0     0    651      0 --:--:-- --:--:-- --:--:--   652
Creating new label: "priority: critical"...
Creating new label: "priority: medium"...
Creating new label: "priority: low"...
Creating new label: "blocked"...
Creating new label: "blocker"...
Creating new label: "stalled"...
Creating new label: "needs estimate"...
Creating new label: "changes requested"...
Creating new label: "has workaround"...
Creating new label: "recommendation"...
Creating new label: "pattern"...
Creating new label: "theming"...
Creating new label: "migration"...
Creating new label: "drupal"...
Creating new label: "ux/design"...
Creating new label: "post-migration"...
Creating new label: "translation"...
Creating new label: "content"...
Creating new label: "documentation"...
Creating new label: "deployment"...
Creating new label: "hotfix"...
Creating new label: "infrastructure"...
Creating new label: "epic"...
Creating new label: "sprint planning"...
Creating new label: "retrospective"...
Creating new label: "user story"...
Creating new label: "revise issue"...
Creating new label: "security"...
Creating new label: "seo"...
Creating new label: "social"...
Creating new label: "performance"...
Creating new label: "x-browser: edge"...
Creating new label: "x-browser: ie10"...
Creating new label: "x-browser: ie11"...
Creating new label: "x-browser: safari"...
Creating new label: "maintenance program"...
Creating new label: "discovery"...
Creating new label: "multilingual"...
Creating new label: "search"...
```

**Comment by amanire** [comment]
👍 verbose worked great in [this repo](https://github.com/isovera/temp-test-verbose/labels).
```sh
$ ./enlabeler.sh -v
Welcome to Enlabeler!
Credentials required: Github username/password
GitHub User: amanire
GitHub Password (or token if using 2fa): 
GitHub Repo (expected format is 'owner/repository' e.g. 'isovera/enlabeler'): isovera/temp-test-verbose
Would you like to delete obsolete labels? (Y/N):Y
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1833  100  1833    0     0   7315      0 --:--:-- --:--:-- --:--:--  7332
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1833  100  1833    0     0   9172      0 --:--:-- --:--:-- --:--:--  9165
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   257  100   257    0     0   1319      0 --:--:-- --:--:-- --:--:--  1324
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   257  100   257    0     0   1550      0 --:--:-- --:--:-- --:--:--  1557
Deleting label: bug
Renaming duplicate to duplicate...
{
  "id": 1161957963,
  "node_id": "MDU6TGFiZWwxMTYxOTU3OTYz",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/duplicate",
  "name": "duplicate",
  "color": "8edee7",
  "default": true,
  "description": "Status - comparable issue or pull request already exists"
}
Deleting label: enhancement
Deleting label: good%20first%20issue
Deleting label: help%20wanted
Deleting label: invalid
Renaming question to question...
{
  "id": 1161957968,
  "node_id": "MDU6TGFiZWwxMTYxOTU3OTY4",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/question",
  "name": "question",
  "color": "8edee7",
  "default": true,
  "description": "Status - a comment in this issue or pull request contains a request for further information"
}
Deleting label: wontfix
Creating new label: "priority: critical"...
{
  "name": "priority: critical",
  "color": "9f0000",
  "description": "Priority level - highest priority and urgent"
}
{
  "id": 1161958171,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MTcx",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/priority:%20critical",
  "name": "priority: critical",
  "color": "9f0000",
  "default": false,
  "description": "Priority level - highest priority and urgent"
}
Creating new label: "priority: medium"...
{
  "name": "priority: medium",
  "color": "f2736f",
  "description": "Priority level - default priority and indicates priority level has been determined"
}
{
  "id": 1161958181,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MTgx",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/priority:%20medium",
  "name": "priority: medium",
  "color": "f2736f",
  "default": false,
  "description": "Priority level - default priority and indicates priority level has been determined"
}
Creating new label: "priority: low"...
{
  "name": "priority: low",
  "color": "ffb3b3",
  "description": "Priority level - lowest priority and should not take precedence over higher priority issues"
}
{
  "id": 1161958182,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MTgy",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/priority:%20low",
  "name": "priority: low",
  "color": "ffb3b3",
  "default": false,
  "description": "Priority level - lowest priority and should not take precedence over higher priority issues"
}
Creating new label: "blocked"...
{
  "name": "blocked",
  "color": "1c6F87",
  "description": "Status - issue is blocked by another issue or dependency"
}
{
  "id": 1161958183,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MTgz",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/blocked",
  "name": "blocked",
  "color": "1c6F87",
  "default": false,
  "description": "Status - issue is blocked by another issue or dependency"
}
Creating new label: "blocker"...
{
  "name": "blocker",
  "color": "1c6F87",
  "description": "Status - issue is blocking other issue(s)"
}
{
  "id": 1161958184,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MTg0",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/blocker",
  "name": "blocker",
  "color": "1c6F87",
  "default": false,
  "description": "Status - issue is blocking other issue(s)"
}
Creating new label: "stalled"...
{
  "name": "stalled",
  "color": "8edee7",
  "description": "Status - work lacks documented progress"
}
{
  "id": 1161958185,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MTg1",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/stalled",
  "name": "stalled",
  "color": "8edee7",
  "default": false,
  "description": "Status - work lacks documented progress"
}
Creating new label: "needs estimate"...
{
  "name": "needs estimate",
  "color": "8edee7",
  "description": "Status - please apply an estimate to this issue before proceeding"
}
{
  "id": 1161958186,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MTg2",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/needs%20estimate",
  "name": "needs estimate",
  "color": "8edee7",
  "default": false,
  "description": "Status - please apply an estimate to this issue before proceeding"
}
Creating new label: "changes requested"...
{
  "name": "changes requested",
  "color": "8edee7",
  "description": "Status - additional work is necessary"
}
{
  "id": 1161958187,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MTg3",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/changes%20requested",
  "name": "changes requested",
  "color": "8edee7",
  "default": false,
  "description": "Status - additional work is necessary"
}
Creating new label: "has workaround"...
{
  "name": "has workaround",
  "color": "8edee7",
  "description": "Status - an alternative solution has been provided for the issue"
}
{
  "id": 1161958188,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MTg4",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/has%20workaround",
  "name": "has workaround",
  "color": "8edee7",
  "default": false,
  "description": "Status - an alternative solution has been provided for the issue"
}
Creating new label: "recommendation"...
{
  "name": "recommendation",
  "color": "8edee7",
  "description": "Status - proposed work that requires authorization"
}
{
  "id": 1161958197,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MTk3",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/recommendation",
  "name": "recommendation",
  "color": "8edee7",
  "default": false,
  "description": "Status - proposed work that requires authorization"
}
Creating new label: "pattern"...
{
  "name": "pattern",
  "color": "a8d49a",
  "description": "Job type: Front-end - development work in pattern library"
}
{
  "id": 1161958206,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MjA2",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/pattern",
  "name": "pattern",
  "color": "a8d49a",
  "default": false,
  "description": "Job type: Front-end - development work in pattern library"
}
Creating new label: "theming"...
{
  "name": "theming",
  "color": "a8d49a",
  "description": "Job type: Front-end - development work in Drupal theme"
}
{
  "id": 1161958207,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MjA3",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/theming",
  "name": "theming",
  "color": "a8d49a",
  "default": false,
  "description": "Job type: Front-end - development work in Drupal theme"
}
Creating new label: "migration"...
{
  "name": "migration",
  "color": "dbff89",
  "description": "Job type: Back-end - development work with Drupal Migrate API"
}
{
  "id": 1161958210,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MjEw",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/migration",
  "name": "migration",
  "color": "dbff89",
  "default": false,
  "description": "Job type: Back-end - development work with Drupal Migrate API"
}
Creating new label: "drupal"...
{
  "name": "drupal",
  "color": "dbff89",
  "description": "Job type: Back-end - Drupal site-building work"
}
{
  "id": 1161958217,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MjE3",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/drupal",
  "name": "drupal",
  "color": "dbff89",
  "default": false,
  "description": "Job type: Back-end - Drupal site-building work"
}
Creating new label: "ux/design"...
{
  "name": "ux/design",
  "color": "dbff89",
  "description": "Job type: Design - creation of design artifacts, often outside of codebase"
}
{
  "id": 1161958233,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MjMz",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/ux/design",
  "name": "ux/design",
  "color": "dbff89",
  "default": false,
  "description": "Job type: Design - creation of design artifacts, often outside of codebase"
}
Creating new label: "post-migration"...
{
  "name": "post-migration",
  "color": "ffeb6d",
  "description": "Job type: Content - work that needs to be performed after the migration"
}
{
  "id": 1161958235,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MjM1",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/post-migration",
  "name": "post-migration",
  "color": "ffeb6d",
  "default": false,
  "description": "Job type: Content - work that needs to be performed after the migration"
}
Creating new label: "translation"...
{
  "name": "translation",
  "color": "ffeb6d",
  "description": "Job type: Content - requires translation of content to another language"
}
{
  "id": 1161958236,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MjM2",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/translation",
  "name": "translation",
  "color": "ffeb6d",
  "default": false,
  "description": "Job type: Content - requires translation of content to another language"
}
Creating new label: "content"...
{
  "name": "content",
  "color": "ffeb6d",
  "description": "Job type: Content - requires adding or updating content within the Drupal CMS"
}
{
  "id": 1161958237,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MjM3",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/content",
  "name": "content",
  "color": "ffeb6d",
  "default": false,
  "description": "Job type: Content - requires adding or updating content within the Drupal CMS"
}
Creating new label: "documentation"...
{
  "name": "documentation",
  "color": "ffdd00",
  "description": "Job type: Other - work related to documentation outside of Drupal UI"
}
{
  "id": 1161958238,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MjM4",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/documentation",
  "name": "documentation",
  "color": "ffdd00",
  "default": false,
  "description": "Job type: Other - work related to documentation outside of Drupal UI"
}
Creating new label: "deployment"...
{
  "name": "deployment",
  "color": "ffa64d",
  "description": "DevOps - issue type used to track preparation and deployment of release to an environment"
}
{
  "id": 1161958239,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MjM5",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/deployment",
  "name": "deployment",
  "color": "ffa64d",
  "default": false,
  "description": "DevOps - issue type used to track preparation and deployment of release to an environment"
}
Creating new label: "hotfix"...
{
  "name": "hotfix",
  "color": "ffa64d",
  "description": "DevOps - deploy changes independently of work on scheduled release in develop branch"
}
{
  "id": 1161958240,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MjQw",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/hotfix",
  "name": "hotfix",
  "color": "ffa64d",
  "default": false,
  "description": "DevOps - deploy changes independently of work on scheduled release in develop branch"
}
Creating new label: "infrastructure"...
{
  "name": "infrastructure",
  "color": "ffa64d",
  "description": "DevOps - setup or management of local, hosting or continuous integration environments"
}
{
  "id": 1161958249,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MjQ5",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/infrastructure",
  "name": "infrastructure",
  "color": "ffa64d",
  "default": false,
  "description": "DevOps - setup or management of local, hosting or continuous integration environments"
}
Creating new label: "epic"...
{
  "name": "epic",
  "color": "e684ad",
  "description": "Planning - epic issues track the progress of multiple issues and can span releases (from ZenHub)"
}
{
  "id": 1161958250,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MjUw",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/epic",
  "name": "epic",
  "color": "e684ad",
  "default": false,
  "description": "Planning - epic issues track the progress of multiple issues and can span releases (from ZenHub)"
}
Creating new label: "sprint planning"...
{
  "name": "sprint planning",
  "color": "e684ad",
  "description": "Planning - work related to project planning"
}
{
  "id": 1161958251,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MjUx",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/sprint%20planning",
  "name": "sprint planning",
  "color": "e684ad",
  "default": false,
  "description": "Planning - work related to project planning"
}
Creating new label: "retrospective"...
{
  "name": "retrospective",
  "color": "e684ad",
  "description": "Planning - issue thread dedicated to sprint or project retrospectives"
}
{
  "id": 1161958252,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MjUy",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/retrospective",
  "name": "retrospective",
  "color": "e684ad",
  "default": false,
  "description": "Planning - issue thread dedicated to sprint or project retrospectives"
}
Creating new label: "user story"...
{
  "name": "user story",
  "color": "e684ad",
  "description": "Planning - issue follows user story template: As a <user type>, I want to <task> so that <goal>"
}
{
  "id": 1161958253,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MjUz",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/user%20story",
  "name": "user story",
  "color": "e684ad",
  "default": false,
  "description": "Planning - issue follows user story template: As a <user type>, I want to <task> so that <goal>"
}
Creating new label: "revise issue"...
{
  "name": "revise issue",
  "color": "e684ad",
  "description": "Planning - issue description is vague, incomplete, or inaccurate"
}
{
  "id": 1161958265,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MjY1",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/revise%20issue",
  "name": "revise issue",
  "color": "e684ad",
  "default": false,
  "description": "Planning - issue description is vague, incomplete, or inaccurate"
}
Creating new label: "security"...
{
  "name": "security",
  "color": "98aeff",
  "description": "Supplementary - work related to security updates, audits or enhancements"
}
{
  "id": 1161958279,
  "node_id": "MDU6TGFiZWwxMTYxOTU4Mjc5",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/security",
  "name": "security",
  "color": "98aeff",
  "default": false,
  "description": "Supplementary - work related to security updates, audits or enhancements"
}
Creating new label: "seo"...
{
  "name": "seo",
  "color": "98aeff",
  "description": "Supplementary - work specifically targeting Search Engine Optimization"
}
{
  "id": 1161958287,
  "node_id": "MDU6TGFiZWwxMTYxOTU4Mjg3",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/seo",
  "name": "seo",
  "color": "98aeff",
  "default": false,
  "description": "Supplementary - work specifically targeting Search Engine Optimization"
}
Creating new label: "social"...
{
  "name": "social",
  "color": "98aeff",
  "description": "Supplementary - implements social sharing features or analytics"
}
{
  "id": 1161958290,
  "node_id": "MDU6TGFiZWwxMTYxOTU4Mjkw",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/social",
  "name": "social",
  "color": "98aeff",
  "default": false,
  "description": "Supplementary - implements social sharing features or analytics"
}
Creating new label: "performance"...
{
  "name": "performance",
  "color": "98aeff",
  "description": "Supplementary - front-end or back-end performance improvements"
}
{
  "id": 1161958298,
  "node_id": "MDU6TGFiZWwxMTYxOTU4Mjk4",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/performance",
  "name": "performance",
  "color": "98aeff",
  "default": false,
  "description": "Supplementary - front-end or back-end performance improvements"
}
Creating new label: "x-browser: edge"...
{
  "name": "x-browser: edge",
  "color": "98aeff",
  "description": "Supplementary - cross-browser compatibility for MS Edge"
}
{
  "id": 1161958299,
  "node_id": "MDU6TGFiZWwxMTYxOTU4Mjk5",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/x-browser:%20edge",
  "name": "x-browser: edge",
  "color": "98aeff",
  "default": false,
  "description": "Supplementary - cross-browser compatibility for MS Edge"
}
Creating new label: "x-browser: ie10"...
{
  "name": "x-browser: ie10",
  "color": "98aeff",
  "description": "Supplementary - cross-browser compatibility for MS Internet Explorer 10"
}
{
  "id": 1161958300,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MzAw",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/x-browser:%20ie10",
  "name": "x-browser: ie10",
  "color": "98aeff",
  "default": false,
  "description": "Supplementary - cross-browser compatibility for MS Internet Explorer 10"
}
Creating new label: "x-browser: ie11"...
{
  "name": "x-browser: ie11",
  "color": "98aeff",
  "description": "Supplementary - cross-browser compatibility for MS Internet Explorer 11"
}
{
  "id": 1161958302,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MzAy",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/x-browser:%20ie11",
  "name": "x-browser: ie11",
  "color": "98aeff",
  "default": false,
  "description": "Supplementary - cross-browser compatibility for MS Internet Explorer 11"
}
Creating new label: "x-browser: safari"...
{
  "name": "x-browser: safari",
  "color": "98aeff",
  "description": "Supplementary - cross-browser compatibility for Safari"
}
{
  "id": 1161958318,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MzE4",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/x-browser:%20safari",
  "name": "x-browser: safari",
  "color": "98aeff",
  "default": false,
  "description": "Supplementary - cross-browser compatibility for Safari"
}
Creating new label: "maintenance program"...
{
  "name": "maintenance program",
  "color": "98aeff",
  "description": "Supplementary - monthly maintenance work"
}
{
  "id": 1161958332,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MzMy",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/maintenance%20program",
  "name": "maintenance program",
  "color": "98aeff",
  "default": false,
  "description": "Supplementary - monthly maintenance work"
}
Creating new label: "discovery"...
{
  "name": "discovery",
  "color": "98aeff",
  "description": "Supplementary - discovery and prototyping work"
}
{
  "id": 1161958336,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MzM2",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/discovery",
  "name": "discovery",
  "color": "98aeff",
  "default": false,
  "description": "Supplementary - discovery and prototyping work"
}
Creating new label: "multilingual"...
{
  "name": "multilingual",
  "color": "98aeff",
  "description": "Supplementary - work related to multilingual development"
}
{
  "id": 1161958337,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MzM3",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/multilingual",
  "name": "multilingual",
  "color": "98aeff",
  "default": false,
  "description": "Supplementary - work related to multilingual development"
}
Creating new label: "search"...
{
  "name": "search",
  "color": "98aeff",
  "description": "Supplementary - work related to internal site search"
}
{
  "id": 1161958338,
  "node_id": "MDU6TGFiZWwxMTYxOTU4MzM4",
  "url": "https://api.github.com/repos/isovera/temp-test-verbose/labels/search",
  "name": "search",
  "color": "98aeff",
  "default": false,
  "description": "Supplementary - work related to internal site search"
}
```

**Comment by hhedden-isovera** [comment]
I tried testing it again, and I can no longer seem to reproduce that error you had with non-verbose mode. As far as I can tell, [all the labels were added this time](https://github.com/isovera/temp-test/labels). Could it have been an authentication or rate limiting issue?

```
$ ./enlabeler.sh 
Welcome to Enlabeler!
Credentials required: Github username/password
GitHub User: hhedden-isovera
GitHub Password (or token if using 2fa): 
GitHub Repo (expected format is 'owner/repository' e.g. 'isovera/enlabeler'): isovera/temp-test
Would you like to delete obsolete labels? (Y/N):Y
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1978  100  1978    0     0   8054      0 --:--:-- --:--:-- --:--:--  8040
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1978  100  1978    0     0   8961      0 --:--:-- --:--:-- --:--:--  8990
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    98  100    98    0     0    602      0 --:--:-- --:--:-- --:--:--   604
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   124  100   124    0     0    778      0 --:--:-- --:--:-- --:--:--   779
Deleting label: bug
Renaming duplicate to duplicate...
Deleting label: enhancement
Deleting label: foo
Deleting label: good%20first%20issue
Deleting label: help%20wanted
Deleting label: invalid
Renaming question to question...
Deleting label: wontfix
Creating new label: "priority: critical"...
Creating new label: "priority: medium"...
Creating new label: "priority: low"...
Creating new label: "blocked"...
Creating new label: "blocker"...
Creating new label: "stalled"...
Creating new label: "needs estimate"...
Creating new label: "changes requested"...
Creating new label: "has workaround"...
Creating new label: "recommendation"...
Creating new label: "pattern"...
Creating new label: "theming"...
Creating new label: "migration"...
Creating new label: "drupal"...
Creating new label: "ux/design"...
Creating new label: "post-migration"...
Creating new label: "translation"...
Creating new label: "content"...
Creating new label: "documentation"...
Creating new label: "deployment"...
Creating new label: "hotfix"...
Creating new label: "infrastructure"...
Creating new label: "epic"...
Creating new label: "sprint planning"...
Creating new label: "retrospective"...
Creating new label: "user story"...
Creating new label: "revise issue"...
Creating new label: "security"...
Creating new label: "seo"...
Creating new label: "social"...
Creating new label: "performance"...
Creating new label: "x-browser: edge"...
Creating new label: "x-browser: ie10"...
Creating new label: "x-browser: ie11"...
Creating new label: "x-browser: safari"...
Creating new label: "maintenance program"...
Creating new label: "discovery"...
Creating new label: "multilingual"...
Creating new label: "search"...
```

**Comment by hhedden-isovera** [comment]
OK, I found the solution. I know my changes on #13 will create some conflicts, but since this solution is pretty simple, they should be easy to resolve.

**Comment by amanire** [comment]
🎉 Success! 
```
$ ./enlabeler.sh
Welcome to Enlabeler!
Credentials required: Github username/password
GitHub User: amanire
GitHub Password (or token if using 2fa): 
GitHub Repo (expected format is 'owner/repository' e.g. 'isovera/enlabeler'): isovera/enlabeler-test-10-1
Would you like to delete obsolete labels? (Y/N):Y
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1849  100  1849    0     0   6183      0 --:--:-- --:--:-- --:--:--  6204
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1849  100  1849    0     0  10116      0 --:--:-- --:--:-- --:--:-- 10159
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6641  100  6641    0     0  31150      0 --:--:-- --:--:-- --:--:-- 31032
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     5  100     5    0     0     30      0 --:--:-- --:--:-- --:--:--    31
Deleting label: bug
Renaming duplicate to duplicate...
Deleting label: enhancement
Deleting label: good%20first%20issue
Deleting label: help%20wanted
Deleting label: invalid
Renaming question to question...
Deleting label: wontfix
Creating new label: "priority: critical"...
Creating new label: "priority: medium"...
Creating new label: "priority: low"...
Creating new label: "blocked"...
Creating new label: "blocker"...
Creating new label: "stalled"...
Creating new label: "needs estimate"...
Creating new label: "changes requested"...
Creating new label: "has workaround"...
Creating new label: "recommendation"...
Creating new label: "pattern"...
Creating new label: "theming"...
Creating new label: "migration"...
Creating new label: "drupal"...
Creating new label: "ux/design"...
Creating new label: "post-migration"...
Creating new label: "translation"...
Creating new label: "content"...
Creating new label: "documentation"...
Creating new label: "deployment"...
Creating new label: "hotfix"...
Creating new label: "infrastructure"...
Creating new label: "epic"...
Creating new label: "sprint planning"...
Creating new label: "retrospective"...
Creating new label: "user story"...
Creating new label: "revise issue"...
Creating new label: "security"...
Creating new label: "seo"...
Creating new label: "social"...
Creating new label: "performance"...
Creating new label: "x-browser: edge"...
Creating new label: "x-browser: ie10"...
Creating new label: "x-browser: ie11"...
Creating new label: "x-browser: safari"...
Creating new label: "maintenance program"...
Creating new label: "discovery"...
Creating new label: "multilingual"...
Creating new label: "search"...
```

**Comment by amanire** [comment]
👍 Confirmed that verbose still works as well.

**Comment by amanire** [comment]
Moved to PR #15 .

**Pull request closed without merging**
